version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  httpd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: httpd_container
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
